user_app/urls.py
from django.urls import path
from . import views

app_name = 'user_app'

urlpatterns = [
    path('register/', views.register, name = 'register'),
    path('profile/', views.profile, name = 'profile'),
]

user_project/urls.py
from django.contrib import admin
from django.urls import path, include
from user_app import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path('login/', views.user_login, name = 'login'),
    path('logout/', views.user_logout, name = 'logout'),
    path('admin/', admin.site.urls),
    path('user_app/', include('user_app.urls')),
]

user_app/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django import forms

# Create your models here.

class UserInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)

    comment = models.CharField(max_length=512)
    profile_icon = models.ImageField(upload_to="profile_icons",blank=True, null=True)
    # file = models.FileField()

user_app/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.db import models
from django import forms
from .models import UserInfo

class UserForm(ModelForm):

    # username = forms.CharField(max_length=25)
    password = forms.CharField(widget=forms.PasswordInput())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for (fname, f) in self.fields.items():
            f.widget.attrs.update({'class':'form-control'})

            # if fname == "password":
            #     f.widget.attrs.update(type='password')

        # self['password'].field.widget.attrs.update({'type':'password'})

    class Meta():
        model = User
        fields = ['username', 'password', 'email', 'first_name', 'last_name']

class UserInfoForm(ModelForm):

    profile_icon = forms.ImageField(required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['user'].widget.attrs.update({'required':False, 'hidden':True})
        # self.fields['profile_icon'].widget.attrs.update({'required':False})

        for (fname, f) in self.fields.items():

            if fname != "user":
                f.widget.attrs.update({'class':'form-control'})

    class Meta():
        model = UserInfo
        fields = '__all__'

class UserProfileForm(ModelForm):

    class Meta():
        model = UserInfo
        fields = '__all__'

user_app/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, logout, login
from django.contrib.auth.models import User
from .models import UserInfo
from .forms import UserInfoForm, UserProfileForm, UserForm
from django.core.exceptions import ValidationError
from django.conf import settings
import os

# Create your views here.

def index(request):

    return render(request, 'user_app/index.html', {})

def process_profile_icon(f):
    filename = os.path.join(settings.MEDIA_ROOT, f.name)
    # print(filename)
    with open(filename, 'wb+') as dest_file:
        for chunk in f.chunks():
            dest_file.write(chunk)

def register(request):

    user_form = UserForm(initial = {'username':'test1',
                                    'password':'pass12345',
                                    'email':'test@test.ru',
                                    'first_name':'First Name',
                                    'last_name':'Last name'})
    user_info_form = UserInfoForm(initial = {   'comment':'bla bla bla',
                                                })

    if request.method == 'POST':

        user_form = UserForm(request.POST)
        user_info_form = UserInfoForm(request.POST, request.FILES)
        # user_info_form = UserInfoForm(request.POST)

        if user_form.is_valid() and user_info_form.is_valid():

            user = user_form.save()
            user_info = user_info_form.save(commit=False)
            user_info.user = user
            user_info.save()

            # TODO save profile_icon

            # if 'profile_icon' in request.FILES:
            #
            #     profile_icon = request.FILES['profile_icon']
                # process_profile_icon(request.FILES['profile_icon'])

            return HttpResponseRedirect(reverse('index'))

        else:
            print("INVALID FORM INFORMATION!")

            print('user_form errors:', len(user_form.errors))
            print('user_info_form errors:', len(user_info_form.errors))

            for (field, errors) in user_form.errors.items():
                print(field, errors)

            for (field, errors) in user_info_form.errors.items():
                print(field, errors)

            # raise ValidationError("FORM VALIDATION ERROR")

    return render(request, 'user_app/register.html', {'user_form':user_form, 'user_info_form': user_info_form})

def user_login(request):

    dict = {'message':{
                'text':'',
                'type':''}}

    if request.method == 'POST':

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username = username, password = password)

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('index'))

        else:
            # raise ValidationError("Wrong username or password")
            dict['message']['text'] = "Wrong username or password"
            dict['message']['type'] = 'error'
            # print("Wrong username or password")
            return render(request, 'user_app/login.html', context=dict)
    else:
        print("login page")

        return render(request, 'user_app/login.html', {})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def profile(request):

    # get current loginned user
    # user = User(current)

    user_form = UserForm(instance = user)
    user_info_form = UserInfoForm(instance = UserInfoForm.objects.get(user = user))

    # if Save button clicked
    if request.method == 'POST':

        # initiate just some fields, like username, password, email
        user_form = UserForm(request.POST, instance = request.user)

        user_info_form = UserInfoForm(request.POST, instance = UserInfoForm.objects.get(user = user))

        if user_form.is_valid() and user_info_form.is_valid():

            user_form.save()
            user_info_form.save()

            print("Profile information was updated successfully")

            # or just register
            return HttpResponseRedirect(reverse('user_app/register', kwargs={'result':'successful'}))

        else:
            raise ValidationError("FORM VALIDATION ERROR")
            # add form validation message
            print("FORM VALIDATION ERROR")

    return render(request, 'user_app/user_profile.html', {'result':'successful'})

@login_required
def download_user_file(request):
    pass

templates/user_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  </head>
  <body>

    <div class="container-fluid">

      <div class="row justify-content-center">
        <div class="col-1">

          <nav class="navbar navbar-default">

              <div class="navbar-header">
                <ul class="nav navbar-nav">
                  <li> <a class="nav navbar-brand" href="{% url 'index' %}">Home</a> </li>
                  <li> <a class="nav navbar-link" href="{% url 'user_app:register' %}">Register</a> </li>

                  {% if user.is_authenticated %}

                  <li> <a class="nav navbar-link" href="{% url 'user_app:profile' %}">User profile</a> </li>
                  <li> <a class="nav navbar-link" href="{% url 'logout' %}">Logout</a> </li>

                  {% else %}

                  <li> <a class="nav navbar-link" href="{% url 'login' %}">Login</a> </li>

                  {% endif %}
                </ul>
              </div>

            </nav>

          </div>
        </div>

    {% block body_block %}
    {% endblock %}

  </div>

  </body>
</html>

templates/user_app/index.html
<!DOCTYPE html>

{% extends 'user_app/base.html' %}

{% block body_block %}

<div class="row">
  <div class="col">

    <div class="jumbotron">

      {% if user.is_authenticated %}

      <h1>Hi, {{user.first_name}}</h1>

      {% else %}

      <h1>Hi. Please login first</h1>

      {% endif %}

    </div>

  </div>

</div>

{% endblock %}

templates/user_app/login.html
<!DOCTYPE html>

{% extends 'user_app/base.html' %}

{% block body_block %}

<div class="row">
  <div class="col-lg-3 col-lg-offset-4
              col-md-3 col-md-offset-4
              col-sm-3 col-sm-offset-4
              col-xs-3 col-xs-offset-4">

      <form action="{% url 'login' %}" method="post">
        {% csrf_token %}

        <div class="form-group">
          <label for="username">User name:</label>
          <input type="text" name="username" class="form-control" style="width:200px" placeholder="Enter username">
        </div>

        <div class="form-group">
          <label for="password">Password:</label>
          <input type="password" class="form-control" style="width:200px" name="password" placeholder="Enter Password">
        </div>

        <div class="form-group">
          {% if message.type == 'error' %}

          <div><p class="bg-danger">{{message.text}}</p></div>
          {% endif %}
        </div>

        <input type="submit" value="Login" class="btn btn-primary">

      </form>


  </div>
</div>



{% endblock %}

templates/user_app/profile.html
<!DOCTYPE html>

{% extends 'user_app/base.html' %}

{% load crispy_forms_tags %}

{% block body_block %}

  <form action="{% url 'user_app:profile' %}" method="post">
    {% csrf_token %}

    {{user_form}}

    {{user_info_form}}

    <input type="submit" class="btn btn-success" value="Save changes">
    <a href="index" class="btn btn-danger">Cancel</a>

  </form>

{% endblock %}

templates/user_app/register.html
<!DOCTYPE html>

{% extends 'user_app/base.html' %}

{% block body_block %}

<div class="row justify-content-center">
  <!-- <div class="col-lg-6 col-lg-offset-3
              col-md-6 col-md-offset-3
              col-sm-6 col-sm-offset-3
              col-xs-6 col-xs-offset-3"> -->

  <div class="col-lg-6">

    <form action="{% url 'user_app:register' %}" enctype="multipart/form-data" method="post">

      {% csrf_token %}

      {{ user_form.as_p }}

      {% for field in user_info_form %}

        {% if not field.html_name == "user" %}

          {{ field.errors }}
          {{ field.label_tag }}
          {{ field }}

        {% endif %}

      {% endfor %}

      <p></p>
      <p><input type="submit" class="btn btn-primary" value="Register"></p>

    </form>

  </div>

</div>

{% endblock %}